name: flutter_login
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  google_fonts: ^3.0.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  get: ^4.6.5
  google_sign_in: ^5.4.3
  flutter_screenutil: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/